package com.researchradar.feature.map

import com.researchradar.core.model.Paper
import com.researchradar.core.model.ResearchMap

object ExportHelper {

    private fun label(map: ResearchMap, paperId: String): String {
        val paper = map.papers.find { it.id == paperId } ?: return paperId
        return paper.shortLabel.ifBlank { paper.title.take(40) }
    }

    fun generateMarkdown(map: ResearchMap): String = buildString {
        appendLine("# Research Map: ${map.topic}")
        appendLine()
        appendLine("Generated by Ereuna on ${map.createdAt}.  ")
        appendLine("Analyzed ${map.stats.totalPapers} papers (${map.stats.fullTextPapers} full-text, ${map.stats.abstractOnlyPapers} abstract-only).")
        appendLine()

        if (map.synthesis.text.isNotBlank()) {
            appendLine("## Synthesis")
            appendLine(map.synthesis.text)
            appendLine()
        }

        if (map.findings.isNotEmpty()) {
            appendLine("## Key Findings")
            map.findings.forEach { finding ->
                val source = finding.paperIds.firstOrNull()?.let { label(map, it) }
                appendLine("### ${finding.text}")
                appendLine("- **Evidence:** \"${finding.evidence.quote}\"" + (source?.let { " — $it" } ?: ""))
                appendLine("- **Confidence:** ${finding.confidence}")
                appendLine()
            }
        }

        if (map.contradictions.isNotEmpty()) {
            appendLine("## Divergent Results")
            map.contradictions.forEach { c ->
                appendLine("### ${c.metric}")
                c.entries.forEach { entry ->
                    appendLine("- ${label(map, entry.paperId)}: ${entry.value} ${entry.unit}")
                }
                appendLine("- **Comparison:** ${c.likelyReason}")
                appendLine()
            }
        }

        if (map.gaps.isNotEmpty()) {
            appendLine("## Research Gaps")
            map.gaps.forEach { gap ->
                appendLine("### ${gap.statement}")
                appendLine("- **Evidence:** ${gap.pattern}")
                if (gap.whyItMatters.isNotEmpty()) {
                    appendLine("- **Why it matters:** ${gap.whyItMatters}")
                }
                if (gap.supportingPaperIds.isNotEmpty()) {
                    appendLine("- **Papers:** ${gap.supportingPaperIds.joinToString(", ") { label(map, it) }}")
                }
                appendLine()
            }
        }

        if (map.experiments.isNotEmpty()) {
            appendLine("## Experiment Suggestions (model-generated)")
            map.experiments.forEach { exp ->
                appendLine("### ${exp.hypothesis}")
                if (exp.setup.isNotBlank()) appendLine("- **Setup:** ${exp.setup}")
                if (exp.variables.isNotEmpty()) appendLine("- **Variables:** ${exp.variables.joinToString(", ")}")
                if (exp.expectedResult.isNotBlank()) appendLine("- **Measure:** ${exp.expectedResult}")
                appendLine("- **Difficulty:** ${exp.difficulty}")
                appendLine()
            }
        }

        if (map.tools.isNotEmpty()) {
            appendLine("## Tools & Datasets")
            map.tools.forEach { tool ->
                appendLine("- **${tool.name}** (${tool.category}): used in ${tool.paperIds.size} papers")
            }
            appendLine()
        }

        appendLine("## Bibliography")
        map.papers.forEachIndexed { i, paper ->
            val header = buildString {
                append("${i + 1}. **${paper.title}**")
                if (paper.year > 0) append(" (${paper.year})")
                if (paper.venue.isNotBlank()) append(". *${paper.venue}*")
                append(".")
            }
            appendLine(header)
            if (paper.authors.isNotEmpty()) {
                appendLine("   - Authors: ${paper.authors.joinToString(", ") { it.name }}")
            }
            appendLine("   - Citations: ${paper.citationCount}" + (paper.doi?.takeIf { it.isNotBlank() }?.let { " · DOI: $it" } ?: ""))
            paper.oaPdfUrl?.takeIf { it.isNotEmpty() }?.let { appendLine("   - Full Text: $it") }
            appendLine()
        }
    }

    private fun bibEscape(text: String): String = buildString {
        text.forEach { ch ->
            when (ch) {
                '{', '}', '&', '%', '#', '_' -> append('\\').append(ch)
                '\\' -> append("\\textbackslash{}")
                else -> append(ch)
            }
        }
    }

    private fun citeKey(paper: Paper, used: MutableSet<String>): String {
        val surname = paper.authors.firstOrNull()?.name?.split(" ")?.lastOrNull()
            ?.replace(Regex("[^A-Za-z0-9]"), "")?.lowercase()?.ifBlank { null } ?: "anon"
        val word = Regex("[A-Za-z]{4,}").find(paper.title)?.value?.lowercase() ?: "paper"
        val base = "$surname${if (paper.year > 0) paper.year else ""}$word"
        var key = base
        var n = 1
        while (!used.add(key)) {
            n += 1
            key = "$base$n"
        }
        return key
    }

    fun generateBibTeX(map: ResearchMap): String = buildString {
        val used = mutableSetOf<String>()
        map.papers.forEach { paper ->
            val isPreprint = paper.venue.contains("arxiv", ignoreCase = true) || paper.id.startsWith("arxiv_")
            appendLine("@${if (isPreprint) "misc" else "article"}{${citeKey(paper, used)},")
            appendLine("  title = {{${bibEscape(paper.title)}}},")
            if (paper.authors.isNotEmpty()) {
                appendLine("  author = {${paper.authors.joinToString(" and ") { bibEscape(it.name) }}},")
            }
            if (paper.venue.isNotBlank() && !isPreprint) appendLine("  journal = {${bibEscape(paper.venue)}},")
            if (paper.id.startsWith("arxiv_")) {
                appendLine("  eprint = {${paper.id.removePrefix("arxiv_")}},")
                appendLine("  archivePrefix = {arXiv},")
            }
            if (paper.year > 0) appendLine("  year = {${paper.year}},")
            paper.doi?.takeIf { it.isNotEmpty() }?.let { appendLine("  doi = {$it},") }
            paper.oaPdfUrl?.takeIf { it.isNotEmpty() }?.let { appendLine("  url = {$it},") }
            appendLine("}")
            appendLine()
        }
    }

    private fun csv(value: String): String = "\"" + value.replace("\"", "\"\"") + "\""

    fun generateCsv(map: ResearchMap): String = buildString {
        appendLine("\"Title\",\"Short Label\",\"Authors\",\"Year\",\"Venue\",\"Citations\",\"Full Text\",\"DOI\",\"Open Access URL\"")
        map.papers.forEach { paper ->
            appendLine(
                listOf(
                    csv(paper.title),
                    csv(paper.shortLabel),
                    csv(paper.authors.joinToString("; ") { it.name }),
                    if (paper.year > 0) paper.year.toString() else "",
                    csv(paper.venue),
                    paper.citationCount.toString(),
                    paper.hasFullText.toString(),
                    csv(paper.doi ?: ""),
                    csv(paper.oaPdfUrl ?: ""),
                ).joinToString(",")
            )
        }
    }
}
